name: GitHub Readme YouTube Cards
on:
  schedule:
    # Runs automatically every hour
    - cron: "0 0 * * *"
  workflow_dispatch: # Allows you to run this script manually

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DenverCoder1/github-readme-youtube-cards@main
        with:
          channel_id: UCc3F5b9XJ4-o1ES47Pp9Epg
